site_name: 大创-大语言-文档
theme:
    name: readthedocs
nav:
    - 主页: index.md
    - lealand:
        - lealand/agentgpt使用报告.md
        - lealand/阅读：ChatGPT原理.md
        - lealand/GPT_prompt吴恩达课程.md
        - lealand/阅读论文WebGPT.md
        - lealand/babyagi使用.md
    - feng:
        - Feng_GPT_Agents_read/Agent-GPT使用体验.md
        - Feng_GPT_Agents_read/Auto-GPT使用体验.md
        - Feng_GPT_Agents_read/GPT-Academic使用体验.md
        - Feng_GPT_Agents_read/GPT-Engineer使用.md